#ifndef CONFIG_H
#define CONFIG_H

#define NUM_FLOORS 10
#define NUM_ROOMS_PER_FLOOR 4
#define ROOM_WIDTH 200
#define ROOM_HEIGHT 50
#define MIN_DISTANCE 10
#define MIN_ROOM 10
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define EXIT_THICKNESS 5
#define SIGN_BOARD_HEIGHT 20
#define SIGN_BOARD_WIDTH 30

#endif